#!/usr/bin/env bash
# Bash script that configures a new Ubuntu machine with Nginx
sudo apt update
sudo apt -y install nginx
echo 'Hello World' > index.html
sudo mv index.html /var/www/html/
sudo service nginx restart
