#!/usr/bin/env bash
# Install HAproxy on 3773-lb-01 server
sudo apt-get update
sudo apt-get -y install haproxy
sudo echo "
frontend front
    bind *:80
    mode http
    default_backend back
backend back
    balance roundrobin
    server 3773-web-01 54.91.227.223:80 check
    server 3773-web-02 107.22.140.255:80 check
" >> /etc/haproxy/haproxy.cfg
sudo service haproxy restart
