#!/usr/bin/env bash
# Install the ufw firewall and setup a few rules.

# Update apt-get and install ufw.
sudo apt-get -y update
sudo apt-get -y install ufw

# Blocks all incoming traffic.
sudo ufw default deny incoming

#Allows all outgoing traffic.
sudo ufw default allow outgoing

# Allow incoming traffic from SSH, HTTPS and HTTP ports respectively.
sudo ufw allow 22
sudo ufw allow 443
sudo ufw allow 80

sudo ufw enable
